{"name": "test_login[user0]", "status": "broken", "statusDetails": {"message": "AttributeError: 'ActionBuilder' object has no attribute 'add_action'. Did you mean: 'key_action'?", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"744155ed-78bf-46dd-a15f-d485cd221bf2\")>\nuser = {'email': 'derly+qa02@vitawallet.io', 'password': 'vitawallet'}\n\n    @pytest.mark.parametrize(\"user\", UserData(\"data/users.csv\").get_users())\n    def test_login(driver, user):\n    \n    \n        # -------------------------\n        # A-A-A DESIGN PATTERN\n        # Arrange 1\n        # -------------------------\n        login_page = LoginPage(driver)\n    \n        # -------------------------\n        # Act 2\n        # -------------------------\n        login_page.login(user[\"email\"], user[\"password\"])\n    \n        # -------------------------\n        # Assert 3\n        # -------------------------\n        #welcome_text_locator = ('xpath', '//android.widget.TextView[@text=\"Welcome\"]')\n        #assert login_page.el.find_element(welcome_text_locator).is_displayed(), \"Login failed for user: {}\".format(user[\"email\"])\n    \n        home_page = HomePage(driver)\n        home_page.quit_pop_up(driver)\n>       home_page.go_crypto(driver)\n\ntests\\test_sample.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\home\\home_page.py:29: in go_crypto\n    Gestures.tap_w3c(driver, 109, 2258)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <appium.webdriver.webdriver.WebDriver (session=\"744155ed-78bf-46dd-a15f-d485cd221bf2\")>\nx = 109, y = 2258\n\n    def tap_w3c(driver, x, y):\n        actions = ActionBuilder(driver)\n        pointer = PointerInput(interaction.POINTER_TOUCH, \"touch\")\n>       actions.add_action(pointer.create_pointer_move(0, \"viewport\", x, y))\n        ^^^^^^^^^^^^^^^^^^\nE       AttributeError: 'ActionBuilder' object has no attribute 'add_action'. Did you mean: 'key_action'?\n\ncore\\gestures.py:12: AttributeError"}, "parameters": [{"name": "user", "value": "{'email': 'derly+qa02@vitawallet.io', 'password': 'vitawallet'}"}], "start": 1759533533929, "stop": 1759533544694, "uuid": "46cd1ba3-7717-497d-96f7-4a9972a1dfbc", "historyId": "cb43fbe24d4c7dde0fd229d0182b8b9e", "testCaseId": "851f638a1293a2d1aa1b69497a224bb7", "fullName": "tests.test_sample#test_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_sample"}, {"name": "host", "value": "DESKTOP-USD8UUS"}, {"name": "thread", "value": "356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_sample"}], "titlePath": ["tests", "test_sample.py"]}